# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
H <- function(d) {
    .Call('_coda_count_H', PACKAGE = 'coda.count', d)
}

#' @export
F <- function(d) {
    .Call('_coda_count_F', PACKAGE = 'coda.count', d)
}

c_ddm <- function(x, alpha) {
    .Call('_coda_count_c_ddm', PACKAGE = 'coda.count', x, alpha)
}

c_dm_fit <- function(X, eps = 0.0001, maxiter = 5000L) {
    .Call('_coda_count_c_dm_fit', PACKAGE = 'coda.count', X, eps, maxiter)
}

#' @export
c_dirichlet_alr_approx <- function(alpha) {
    .Call('_coda_count_c_dirichlet_alr_approx', PACKAGE = 'coda.count', alpha)
}

#' @export
c_logistic_ilr_approximation <- function(d) {
    .Call('_coda_count_c_logistic_ilr_approximation', PACKAGE = 'coda.count', d)
}

#' @export
c_logistic_alr_approximation <- function(d) {
    .Call('_coda_count_c_logistic_alr_approximation', PACKAGE = 'coda.count', d)
}

#' @export
c_gaussian_product <- function(pars1, pars2) {
    .Call('_coda_count_c_gaussian_product', PACKAGE = 'coda.count', pars1, pars2)
}

#' @export
c_gaussian_division <- function(pars1, pars_res) {
    .Call('_coda_count_c_gaussian_division', PACKAGE = 'coda.count', pars1, pars_res)
}

#' @export
c_d_lrnm_gaussian_approx <- function(x, mu, sigma, Binv) {
    .Call('_coda_count_c_d_lrnm_gaussian_approx', PACKAGE = 'coda.count', x, mu, sigma, Binv)
}

#' @export
c_posterior_alr_approximation <- function(x, mu, sigma) {
    .Call('_coda_count_c_posterior_alr_approximation', PACKAGE = 'coda.count', x, mu, sigma)
}

#' @export
c_m1_lrnm_gaussian_approx <- function(x, mu, sigma, Binv) {
    .Call('_coda_count_c_m1_lrnm_gaussian_approx', PACKAGE = 'coda.count', x, mu, sigma, Binv)
}

#' @export
c_m2_lrnm_gaussian_approx <- function(x, mu, sigma, Binv) {
    .Call('_coda_count_c_m2_lrnm_gaussian_approx', PACKAGE = 'coda.count', x, mu, sigma, Binv)
}

#' @export
c_d_lrnm_hermite <- function(x, mu, sigma, Binv, order) {
    .Call('_coda_count_c_d_lrnm_hermite', PACKAGE = 'coda.count', x, mu, sigma, Binv, order)
}

#' @export
c_m1_lrnm_hermite <- function(x, mu, sigma, Binv, order) {
    .Call('_coda_count_c_m1_lrnm_hermite', PACKAGE = 'coda.count', x, mu, sigma, Binv, order)
}

#' @export
c_m2_lrnm_hermite <- function(x, mu, sigma, Binv, order) {
    .Call('_coda_count_c_m2_lrnm_hermite', PACKAGE = 'coda.count', x, mu, sigma, Binv, order)
}

c_d_lrnm_hermite_ <- function(x, mu, sigma, Binv, order = 100L, step_by = 100L, eps = 0.000001, max_steps = 10L) {
    .Call('_coda_count_c_d_lrnm_hermite_', PACKAGE = 'coda.count', x, mu, sigma, Binv, order, step_by, eps, max_steps)
}

c_m1_lrnm_hermite_ <- function(x, mu, sigma, Binv, order = 100L, step_by = 100L, eps = 0.000001, max_steps = 10L) {
    .Call('_coda_count_c_m1_lrnm_hermite_', PACKAGE = 'coda.count', x, mu, sigma, Binv, order, step_by, eps, max_steps)
}

c_m2_lrnm_hermite_ <- function(x, mu, sigma, Binv, order = 100L, step_by = 100L, eps = 0.000001, max_steps = 10L) {
    .Call('_coda_count_c_m2_lrnm_hermite_', PACKAGE = 'coda.count', x, mu, sigma, Binv, order, step_by, eps, max_steps)
}

c_fit_lrnm_hermite_ <- function(X, mu0, sigma0, Binv, order = 100L, step_by = 100L, eps = 0.000001, max_steps = 10L, em_max_steps = 10L) {
    .Call('_coda_count_c_fit_lrnm_hermite_', PACKAGE = 'coda.count', X, mu0, sigma0, Binv, order, step_by, eps, max_steps, em_max_steps)
}

#' @export
ldnormal2 <- function(H, mu, inv_sigma) {
    .Call('_coda_count_ldnormal2', PACKAGE = 'coda.count', H, mu, inv_sigma)
}

#' @export
ldnormal <- function(H, mu, inv_sigma) {
    .Call('_coda_count_ldnormal', PACKAGE = 'coda.count', H, mu, inv_sigma)
}

#' @export
lpmultinomial_const <- function(x) {
    .Call('_coda_count_lpmultinomial_const', PACKAGE = 'coda.count', x)
}

#' @export
lpnm_join <- function(x, mu, inv_sigma, P, H) {
    .Call('_coda_count_lpnm_join', PACKAGE = 'coda.count', x, mu, inv_sigma, P, H)
}

#' @export
lpnm_join_no_constant <- function(x, mu, inv_sigma, p, h) {
    .Call('_coda_count_lpnm_join_no_constant', PACKAGE = 'coda.count', x, mu, inv_sigma, p, h)
}

#' @export
lpnm_join_deriv <- function(I, a, mu, inv_sigma, x) {
    .Call('_coda_count_lpnm_join_deriv', PACKAGE = 'coda.count', I, a, mu, inv_sigma, x)
}

#' @export
lpnm_join_deriv2 <- function(I, J, a, mu, inv_sigma, x) {
    .Call('_coda_count_lpnm_join_deriv2', PACKAGE = 'coda.count', I, J, a, mu, inv_sigma, x)
}

#' @export
lpnm_join_maximum_alr <- function(x, mu_alr, inv_sigma_alr, a, eps, max_iter) {
    .Call('_coda_count_lpnm_join_maximum_alr', PACKAGE = 'coda.count', x, mu_alr, inv_sigma_alr, a, eps, max_iter)
}

c_rmultinomial_Rcpp <- function(P, vsize) {
    .Call('_coda_count_c_rmultinomial_Rcpp', PACKAGE = 'coda.count', P, vsize)
}

c_rmultinomial <- function(P, vsize) {
    .Call('_coda_count_c_rmultinomial', PACKAGE = 'coda.count', P, vsize)
}

c_rdirichlet <- function(n, alpha) {
    .Call('_coda_count_c_rdirichlet', PACKAGE = 'coda.count', n, alpha)
}

c_rdirichletmultinomial <- function(alpha, size) {
    .Call('_coda_count_c_rdirichletmultinomial', PACKAGE = 'coda.count', alpha, size)
}

#' @export
c_rnormal <- function(n, mu, sigma) {
    .Call('_coda_count_c_rnormal', PACKAGE = 'coda.count', n, mu, sigma)
}

#' @export
c_rnormalSimplex <- function(n, mu, sigma, Binv) {
    .Call('_coda_count_c_rnormalSimplex', PACKAGE = 'coda.count', n, mu, sigma, Binv)
}

#' @export
c_rnormalmultinomial <- function(mu, sigma, size, Binv) {
    .Call('_coda_count_c_rnormalmultinomial', PACKAGE = 'coda.count', mu, sigma, size, Binv)
}

pinv <- function(X) {
    .Call('_coda_count_pinv', PACKAGE = 'coda.count', X)
}

c_simplex_lattice <- function(K, SIZE) {
    .Call('_coda_count_c_simplex_lattice', PACKAGE = 'coda.count', K, SIZE)
}

